### ISSUE TITLE
Publication Date Facet Not Working

### ISSUE THREAD

**Issue by gerbie-goober** [digitalutsc/facets_year_range#3]
**Issue:** The Publication Date Facet for many/all sites are working properly. If a date range is entered, often times, search results are shown where these objects don't fit the date range. 
**Desired:** Objects in the results that fit the date range, or "No Results"

**Example 1:** 
- Reproduce issue on Arab Women's Writing Site: 
  - In the Publication Date Facet, enter the date range: "1990" to "2000" > Press "Refine"
  - The results don't fit that range (e.g. https://arabww.digital.utsc.utoronto.ca/node/1404)
  - Also, please note the url for entering said data range: https://arabww.digital.utsc.utoronto.ca/node/1?f%5B0%5D=collection_members_year_created%3A2003 

**Example 2:**
- Reproduce issue on Learn Site:
  - Click "Browse Collection" > Click on any object
  - Click on the subject field (or any other metadata field that is linkable) 
  - The Publication Date Facet is no longer available

  - Also, same issue on the Learn Site as described in the first example. Please note this result from entering the date range ("1990" to "2000"): https://learn.digital.utsc.utoronto.ca/learning-objects-catalog?f%5B0%5D=collection_members_year_created%3A2022

**Comment by gerbie-goober** [comment]
**Side note:** semantics-wise, might be misleading to use Publication Date if only filters by Year
**Suggestion:** Publication Year

**Comment by kylehuynh205** [comment]
Fixed the issue by change "URL alias" to `collection_member_publication_year` for the facets settings

<img width="714" alt="image" src="https://github.com/digitalutsc/facets_year_range/assets/7862086/b1e1ee34-c56a-44dc-9f67-cd043f548117">



... and things start to work, maybe there. is some hard code to this field: `collection_member_publication_year`
